node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerguy') {
        def app = docker.build("guyc82/docker-nodejs-demo2:${commit_id}", './basics').push()
        def app_latest = docker.build("guyc82/docker-nodejs-demo2:latest", './basics').push()
        
     }
   }
   stage('docker run') {
     sh label: '', script: '''
      docker run --rm -tid --name docker_test -p 3000 guyc82/docker-nodejs-demo2:latest
      docker kill docker_test
      
      '''
     }
   }
